### PR TITLE
Cmake changes

### PR DESCRIPTION
**Pull request by jongough**

### CODE REVIEW

**Comment by leamas** [comment]
Just  a drive-by comment: I saw that you basically do ` INCLUDE(CPack)` *before* setting the CPACK_\* variables. This will not fly, CPack only sees the variables defined when it is included.


Besides: this effort to clean up the mess is really, really nice...

**Comment by rgleason** [comment]
As is all of your work Alec!  Thanks to all of you. This is a great improvement.

**Comment by mauroc** [comment]
travis macos build appears stuck indefinitely - merging PR nevertheless

**Comment by jongough** [comment]
INCLUDE(CPack) is the last statement in PluginPackage.cmake after all the CPACK_** variables have been set. Where did you see that was not the case?

**Comment by leamas** [comment]
> INCLUDE(CPack) is the last statement in PluginPackage.cmake

Indeed

> Where did you see that was not the case?

I failed to read a patch... sorry for the noise.

**Pull request merged**
