### PR TITLE
v1.3.2.1 Frontend2 + Mauro Personal Config

### PR DESCRIPTION
**Pull request by rgleason**
Mauro,
I changed the version from 1.3.1 to 1.3.2.1 because there was an existing tag with 1.3.1 and I used the command  git push --tag origin frontend2:frontend2  to push it up from local to my repository.

Note that all builds will fail on my repository, because I have changed the CMakeLists.txt to be configured to your personal setup.  However I hope they will work on your repository. It may take some adjustments.  Also I have noticed that the flatpak build and the travis builds seem to require a kick  like "Rerun from start" or "Rerun from fail".  The one of the travis build seems to be failing due to time longer than 50 minutes!  (we have added a "travis - wait" command which lengthens the time to fail.

Also, there appear to be conflicts that need resolution.  I don't know what they are but normally you should favor the configuration Jon and I are pushing to you. (IE files in these directories, buildosx, debian, mingw, cmake, ci, circleci also files .travis.yml, appveyor.yml and cmakelists.txt

Lets hope this works.  Hopefully you can get it working and then push it to master.

I was able to resolve the conflict in cmakelists.txt.  online.  The conflict was the section where the Version number was, It had a choice of your current version or the new one.. I picked the new one. It seems to be building now.

I think it is failing because of one of these reasons:
1. Certificate problem
2.  Circleci needs to be enabled to use this branch in githhub.
3.  Enable circleci download of the repository from  github - permissions.
4. Same for travis.
5. If there is a deployment problem, it may require using the CLOUDSMITH_API_KEY in circleci or travis.    

Circleci Errors
```
Checking raw package upload parameters ... -/ERROR
Failed to validate upload parameters! (status: 404 - Not Found)
Detail: Not found.
Hint: This usually means the user/org is wrong or not visible.
```

Another problem

drwxr-xr-x  6 circleci circleci  4096 Apr 15 13:58 src

+ cloudsmith push raw --republish --no-wait-for-sync --name squiddio_pi-ubuntu-16.04-xenial-metadata --version 1.3.2.1+1229.19c5da8 --summary 'squiddio opencpn plugin metadata for automatic installation' mauro-calvi/-manual /home/circleci/project/build/squiddio_pi-1.3.2.1_ubuntu-16.04-xenial.xml

This path does not look right.  Should be  mauro-calvi/squiddi-manual
mauro-calvi/-manual /home/

After that last commit, it is better, but there is a space after the word manual which you can barely see! Will fix.
  " mauro-calvi/squiddio-manual /home/circleci/pro"

Well, I've looked at both CMakeLists.txt and cmake/in-line/cloudsmith-upload.sh.in  and they both look ok to me.  I am not even sure if this space is a problem. So I would check the earlier list on your side.

A good sign, appveyor built and deployed.
Maybe Jon can identify why the space is there:

```
mauro-calvi/squiddio-manual /home/circleci/project/build/squiddio_pi-1.3.2.1_ubuntu-18.04-bionic.xml
Checking raw package upload parameters ... -/ERROR

```

Mauro, I now think that this space in the path is not a problem because both Travis and Appveyor deployed.   So now the remaining question is if Circleci has the right permissions to upload to Cloudsmith.   So you need to enable the Frontend2 branch somehow, or use your CLOUDSMITH_API_KEY in the Circleci  squiddio branch frontend2? ??

### CODE REVIEW

**Comment by rgleason** [comment]
Mauro, you'd best accept this PR soon because I am going to reset my personal setting with another commit, and if this PR is still open, those commits will be added automatically.

**Comment by rgleason** [comment]
The circleci are all failing because they do not have permission from circleci for PR to build.
When you merge most if not all should work.  Or you  can enable PR on circleci if you want to check them.

**Comment by mauroc** [comment]
well, whatever you did, worked like magic!

image

I didn't have to do anything other than accept the PR. The fac that the MacOS build worked is icing on the cake.

Sorry it took so long and thanks for all the work you put into this, Rick

**Comment by rgleason** [comment]
Mauro,  Good, That is what I was hoping.  Thanks. I was learning and learned a lot from Jon Gough who was very very patient. Now I think I can change my CMakeLists.txt back to my personal settings and that will work.  Jon has made this task very simple, all in one place.
We may have to fix an environment build once in awhile because they do change.

The next step is to check your repository in Cloudsmith and get the xml's into the Beta Catalog.
https://cloudsmith.io/~mauro-calvi/repos/squiddio-manual/packages/?page=1
Download each of the recent xml files to a local directory.
From your local github directory, 

`git clone https://github.com/OpenCPN/plugins.git plugins
`
You want to clone this. https://github.com/OpenCPN/plugins
Then checkout the Beta branch.

git checkout -b Beta
git fetch

Then copy your metada files (after looking at some of them for errors) to the metadata directory.
Then, reading the README run the python script to join the metadata files into one file call ocpn_plugin.xml   Then run the URL check on the file to make sure all urls are good.

Then you can make a PR to Dave (bdbcat) at OpenCPN/plugins

If you have any questions just ask me here.

Thank you for all your work on the interface. I was trying it out a little to learn about that. I think I understand this is an intermediate step showing the mechanizms.

**Pull request merged**
