### PR TITLE
move config of xml files from CMakeLists.txt to PluginConfigure.cmake

### PR DESCRIPTION
**Pull request by jongough**
Update version.h.in to include 'TWEAK' as a new version value

### CODE REVIEW

**Comment by mauroc** [comment]
not sure if I handled the conflict correctly. Looks like someone had inserted the if (OCPN_FLATPAK) clause, while someone else was modifying the same lines in the master? (I have not touched this file). In any event, I accepted the if (OCPN_FLATPAK) clause

**Comment by rgleason** [comment]
Sorry Jon, Who has the railroad man's torch here?  I guess Alec got it this time. We need some semaphore signals.

**Comment by rgleason** [comment]
Alec, Flatpak gets moved a lot lately. If Jon's solution works, why not use it? 
https://github.com/mauroc/squiddio_pi/commit/58fd8cabdb92aea2603af896d1a6ef2e686357d0

**Comment by jongough** [comment]
I was attempting to make the cmake process more sensible and clean. However, this does not appear to be what is wanted/required. So I will now stop making any changes as I am always playing catch up.

**Comment by rgleason** [comment]
Mauro,
Please freeze the merges from Alec for the moment while we sort this out. Thanks.

Jon, 
I made a new local & public branch "pluginconfigure.cmake"
which is based upon the current mauroc/master, however it has been configured to run on my cloudsmith and circleci accounts and it deploys files to Cloudsmith and Github.

https://github.com/rgleason/squiddio_pi/commits/plugin-configure.cmake

I'd like to rebase or make a patch that I can apply onto the pluginconfigure.cmake branch.
How would you suggest I do that?

The other thing is you are a collaborator on my squiddio repository, so I believe you can push the changes to pluginconfigure.cmake and they will run and deploy at though I did it.

**Comment by rgleason** [comment]
Actually I think I need to
1. from mauroc/master checkout a new jg-test branch
2. revert back to https://github.com/jongough/squiddio_pi/commit/af43bbcb5322a65e5a0c581d31515c248adaa8d6 
3. pull your changes onto the jg-test branch.
4. see how they build and deploy

**Comment by rgleason** [comment]
Jon,
I did the above and most of it succeeded build, except flatpak. I hope the circleci report will give you some clues. You can press the button to rerun it, since you are a collaborator.
https://github.com/rgleason/squiddio_pi/commits/jg-test
https://github.com/rgleason/squiddio_pi/runs/270822864

**Comment by rgleason** [comment]
Mauro,
Please still pause while we get this sorted.

**Comment by jongough** [comment]
Hi,
I have been playing with this in my own version of squiddio. I now have a build process for flatpak that works with the full cmake process. All it required was to ensure that these two lines were added to 'docker-build-flatpak.sh':
su -c "dnf install -y sudo dnf-plugins-core"
sudo dnf builddep  -y ci/opencpn-fedora.spec

I have tested this by starting the travis-build-flatpak.sh, but I would assume that 'circleci-buil-flatpak.sh' will work as it seems to run the same docker commands.

The full cmake will now run quite happily. So in my testing the flatpak stuff is in the PluginPackage.cmake file and I no longer require the cmake process to work around the incompatability.

Do you want me to submit a patch for this?

**Comment by mauroc** [comment]
> Do you want me to submit a patch for this?

@jongough : just to clarify: it seems like the flatpack build process already works on Circleci. 
image

what problem is the patch meant to address? Thanks

**Comment by jongough** [comment]
The patch cleans up the cmake files (removes the need to have if(OCPN_FLATPAK) statements in most cmake files and moves the flatpak packaging cmake code to the PluginPackage.cmake. It also moves cmake files out of the root directory into the cmake directory.

These changes are to make the cmake files more consistent by grouping similar activities into the relevant files. It also cleans up the file hierarchy a bit. The changes should have no impact on the build process just helps with human understanding.

**Comment by mauroc** [comment]
sounds good. Feel free to submit a PR if you need to

**Pull request closed without merging**
